### ISSUE TITLE
fix binary wheel building & uploading to pypi

### ISSUE THREAD

**Issue by ctb** [oxli-bio/oxli#15]

**Comment by Adamtaranto** [comment]
Had another look at this, not sure what is wrong with CI.yml workflow. 

Have you set up the PyPi token for this project?

**Comment by ctb** [comment]
Followed https://docs.pypi.org/trusted-publishers/adding-a-publisher/, and added GitHub oxli-bio/oxli as a trusted publisher:

<img width="665" alt="Screenshot 2024-09-22 at 5 55 58 PM" src="https://github.com/user-attachments/assets/527d1537-9963-4762-a8f5-5984351b2e85">

Shall we try to cut a new release once #31 and #45 are merged, and see if it works?

Hmm, maybe I actually enabled trusted publishing instead of token auth 🤔 - see:

<img width="777" alt="Screenshot 2024-09-22 at 5 58 37 PM" src="https://github.com/user-attachments/assets/1c9271a4-5886-48e9-bc4b-65deed0fe590">

Also, what's your pypi username?

**Comment by Adamtaranto** [comment]
pypi username is adamtaranto

**Comment by Adamtaranto** [comment]
Good to go on making a new release

**Comment by ctb** [comment]
well, it is now running the right thing :) but now says:

> 💥 maturin failed
> Caused by: Credentials not found and non-interactive mode is enabled

**Comment by ctb** [comment]
(this was also a useful link for getting the YAML right in the CI release section: https://docs.pypi.org/trusted-publishers/using-a-publisher/)

**Comment by ctb** [comment]
It worked! Now to test it out on a real release...

**Comment by ctb** [comment]
https://pypi.org/project/oxli/0.3.0rc3/#files

**Comment by ctb** [comment]
v0.3.0 released and uploaded to PyPI! Now to see if conda-forge picks it up :)

https://pypi.org/project/oxli/#files
