### ISSUE TITLE
add `black` to handle python code formatting

### ISSUE THREAD

**Issue by ctb** [oxli-bio/oxli#17]

**Comment by Adamtaranto** [comment]
I'm using Ruff locally in keeping with the Rust for everything theme (which would be why the pytests have been reformatted). 

Do you want to have a pre-commit to run Ruff / Black on python files for new commits?

- [Ruff for Github Actions](https://github.com/chartboost/ruff-action)
- [Ruff with github actions](https://dev.to/ken_mwaura1/automate-python-linting-and-code-style-enforcement-with-ruff-and-github-actions-2kk1)

**Comment by Adamtaranto** [comment]
@ctb how does that sound? alt if you have an example of a different action you want to use I can set it up here.

**Comment by ctb** [comment]
sounds good to me!
