### ISSUE TITLE
Serialising KmerCountTables

### ISSUE THREAD

**Issue by Adamtaranto** [oxli-bio/oxli#25]
Serialise `KmerCountTable` objects to disk and load saved objects.

Check out [Serde](https://serde.rs/#data-formats) and [Bincode](https://github.com/bincode-org/bincode).

Serde supports read/write of Python Pickle format. Could make things easier when loading back into Python.

**Comment by ctb** [comment]
serde is great! we use it in sourmash.

**Comment by Adamtaranto** [comment]
Leaning towards writing tables to JSON and compressing with Gzip (instead of writing to binary). Readability could be helpful later for users to report weird behaviour. 

I'll also add a version attribute to `KmerCountTable` in case we do anything that affects backwards compatibility in the future.
