### ISSUE TITLE
support Jaccard and angular similarity calculations

### ISSUE THREAD

**Issue by ctb** [oxli-bio/oxli#39]
these are both calculated in sourmash, albeit for FracMinHash sketches.

ref for angular similarity: [wikipedia](https://en.wikipedia.org/wiki/Cosine_similarity#Angular_distance_and_similarity)

abundance projection has also been useful over in sourmash, in which the abundances from one set of k-mers are projected onto the (flat) k-mers from another; the specific use case in sourmash has been to support reference genome abundance estimation in metagenomes. we might do something similar here.

**Comment by Adamtaranto** [comment]
@ctb can you point me at some code for the abundance projection stuff?

**Comment by ctb** [comment]
[This](https://github.com/sourmash-bio/sourmash/blob/latest/src/sourmash/search.py#L858) is the clearest example I can find quickly - but maybe not clear enough? :)

The idea is you take some set of k-mers, and then "borrow" the abundances for them from another set of k-mers. Pseudocode:

```python
# a, b are two collections of k-mers
isect = a.intersection(b)

a_onto_b = 0 # calculate projected sum
for kmer in isect:
    a_onto_b += b.abund(kmer)
```

so I guess if I were going to be more precise I would say: the projection here is of the abundances from either a or b onto the intersection of a and b.

**Comment by Adamtaranto** [comment]
So its just the sum of all the counts in b for kmers that occur in a & b?

**Comment by ctb** [comment]
yep! The linear algebra analogy would be something like projecting a vector into a subspace, I think.
