### ISSUE TITLE
Rename allow_bad_kmers

### ISSUE THREAD

**Issue by Adamtaranto** [oxli-bio/oxli#51]
Should we rename the [allow_bad_kmers](https://github.com/oxli-bio/oxli/blob/main/src/lib.rs#L394-L403) option in `consume` to make more intuitive?

This opt is passed to SeqToHashes as the `force` argument. 

Behaviour seems to be:   
True - Skip over bad kmers, do not hash them, do not raise error.
False - hash/count all kmers up to the first non-DNA character then raise an error and stop processing the input sequence.

I would expect allow_bad_kmers = True to hash all kmers including those with non-dna characters, and False to skip the bad kmers and carry on with processing.

Suggest change option to `skip_bad_kmers`

**Comment by Adamtaranto** [comment]
This definition is at odds with the [API notes](https://github.com/oxli-bio/oxli/blob/main/doc/api.md)

@ctb can you clarify?

**Comment by ctb** [comment]
I like the suggestion to use `skip_bad_kmers`!
